// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using elbanna.Data;

#nullable disable

namespace elbanna.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("item");

                    b.HasKey("Id");

                    b.ToTable("ic_item");
                });

            modelBuilder.Entity("Purchase", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("costcenterId")
                        .HasColumnType("int");

                    b.Property<string>("dealer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("dealerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("insertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("insertUserId")
                        .HasColumnType("int");

                    b.Property<string>("invoiceNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isreviewed")
                        .HasColumnType("bit");

                    b.Property<string>("item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("itemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("lastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("lastUpdateUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("processDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("unitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("costcenterId");

                    b.ToTable("pr_purchase");
                });

            modelBuilder.Entity("elbanna.Models.ConInvoice", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal?>("balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("costcenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("costcenterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("factor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("factorValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("insertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("invoiceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("invoiceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isRefund")
                        .HasColumnType("bit");

                    b.Property<bool?>("isReviewed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("lastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("lastUpdateUserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("net")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("payFor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("payForId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("con_invoice");
                });

            modelBuilder.Entity("elbanna.Models.ConPayFor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("factor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("factorValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("payFor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("con_payFor");
                });

            modelBuilder.Entity("elbanna.Models.Dealer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<string>("dealer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dealer");

                    b.Property<bool>("isBank")
                        .HasColumnType("bit")
                        .HasColumnName("isBank");

                    b.Property<string>("nationalId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nationalId");

                    b.HasKey("id");

                    b.ToTable("acc_Dealer");
                });

            modelBuilder.Entity("elbanna.Models.acc_CostCenter", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("building")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("costCenter")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("costCenter");

                    b.Property<string>("floor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("floorUnit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("acc_CostCenter");
                });

            modelBuilder.Entity("elbanna.Models.acc_CreditAccount", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("creditAcc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("creditAcc");

                    b.HasKey("id");

                    b.ToTable("acc_CreditAccount");
                });

            modelBuilder.Entity("elbanna.Models.acc_Daily", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("costcenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("costcenterId")
                        .HasColumnType("int");

                    b.Property<string>("dealer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dealerCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("fromAcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("insertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("insertUserId")
                        .HasColumnType("int");

                    b.Property<string>("invoiceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isAllowed")
                        .HasColumnType("bit");

                    b.Property<bool?>("isReviewed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("lastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("lastUpdateUserId")
                        .HasColumnType("int");

                    b.Property<string>("lastUpdateUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("net")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("processDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("toAcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.ToTable("acc_Daily");
                });

            modelBuilder.Entity("elbanna.Models.acc_invoiceCode", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("invoiceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("invoiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("acc_invoiceCode");
                });

            modelBuilder.Entity("elbanna.Models.hr_user", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("allowFutureSaveDays")
                        .HasColumnType("int");

                    b.Property<int?>("allowSaveDays")
                        .HasColumnType("int");

                    b.Property<int?>("allowShowDays")
                        .HasColumnType("int");

                    b.Property<bool?>("allowShowOtherData")
                        .HasColumnType("bit");

                    b.Property<bool?>("canPaid")
                        .HasColumnType("bit");

                    b.Property<bool?>("canReview")
                        .HasColumnType("bit");

                    b.Property<bool?>("canUpdateCustody")
                        .HasColumnType("bit");

                    b.Property<bool?>("islogged")
                        .HasColumnType("bit");

                    b.Property<string>("job")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("jobId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("lastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("hr_user");
                });

            modelBuilder.Entity("Purchase", b =>
                {
                    b.HasOne("elbanna.Models.acc_CostCenter", "CostCenter")
                        .WithMany()
                        .HasForeignKey("costcenterId");

                    b.Navigation("CostCenter");
                });
#pragma warning restore 612, 618
        }
    }
}
